### ISSUE TITLE
is there a way to 'place' an item along a path without starting the animation?

### ISSUE THREAD

**Issue by luboslives** [yairEO/pathAnimator#8]
For example, I have a bunch of cars on a track that need to idle at the grid until we tell them to start moving. Preferably I would say car1 at 99% of the path, car2 at 98%, etc. It seems like pathAnimator would have most of the info I need to accomplish this. 

Currently they all sit at x0, y0 and I use SVG translate to move them. Could I get the x,y point of my path at 99%, 98% etc?

**Comment by luboslives** [comment]
Answering my own question here....

Looking into this led me to [SVGPathElement](https://developer.mozilla.org/en/docs/Web/API/SVGPathElement). I see that you use some of those methods in pathAnimator.

So it looks like I can
1. use `.pathAnimator.path.getTotalLength()` to get a numerical length.
2. multiply that number by my desired percentages. 
3. then find the x,y point of that percentage with `.pathAnimator.path.getPointAtLength(number)`

I'm guessing the path we use these methods on has to be created as a namespaced SVG element in our script first... seeing as I can get this info from the current pathAnimator path but not my existing SVG art.

**Comment by yairEO** [comment]
you have everything there. the code is extremely small...you have to be creative
