### ISSUE TITLE
Failed to execute 'getPointAtLength' on 'SVGGeometryElement': The provided float value is non-finite.

### ISSUE THREAD

**Issue by tyrellrummage** [yairEO/pathAnimator#9]
I tried with 10 different paths, all same the same.

**Comment by jamessimo** [comment]
Got the same issue here, the demo works fine but the basic example produces this error with many diffrent path types (including default one)

**Comment by yairEO** [comment]
Please post the `path` here so I could test it

**Comment by AliRezaBeitari** [comment]
@tyrellrummage @jamessimo, In this line: `easing = function(t) { t*(2-t); };` @yairEO forgot to put `return` befor ` t*(2-t);`. So the code should be like this: `easing = function(t) { return t*(2-t); };`

**Comment by tyrellrummage** [comment]
@AliRezaBeitari thanks!

**Comment by yairEO** [comment]
fixed! also updated the whole code, so take a look
